# Generated by Django 6.0 on 2025-12-09 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_category_description_alter_category_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Current order status', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('shipping_address', models.TextField(help_text='Full shipping address')),
                ('shipping_city', models.CharField(help_text='City', max_length=100)),
                ('shipping_country', models.CharField(help_text='Country', max_length=100)),
                ('shipping_phone', models.CharField(help_text='Contact phone', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Total before shipping and tax', max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, help_text='Shipping fee', max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Final total (subtotal + shipping + tax)', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Order notes from customer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name at order time', max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, help_text='Price at order time', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity ordered')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(help_text='Product ordered', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
