# Generated by Django 6.0 on 2025-12-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.URLField(blank=True, help_text='Product image URL at order time', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_slug',
            field=models.CharField(blank=True, help_text='Product slug for linking', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price at order time', max_digits=10),
        ),
    ]
