# Generated by Django 6.0 on 2025-12-14 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_description_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name (e.g., Apple, Nike, Samsung)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name', max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Brand logo (recommended: 200x200px)', null=True, upload_to='brands/')),
                ('description', models.TextField(blank=True, help_text='Brief description of this brand')),
                ('website', models.URLField(blank=True, help_text='Official brand website')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shipping method name (e.g., Standard Shipping)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of shipping method')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Shipping cost', max_digits=8)),
                ('estimated_days_min', models.PositiveIntegerField(default=3, help_text='Minimum delivery days')),
                ('estimated_days_max', models.PositiveIntegerField(default=7, help_text='Maximum delivery days')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default shipping option')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order amount for free shipping (leave empty if not applicable)', max_digits=8, null=True)),
                ('regions', models.CharField(default='worldwide', help_text="Comma-separated country codes or 'worldwide'", max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which category appears (lower = first)'),
        ),
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('laptop', 'Electronics'), ('shirt', 'Fashion'), ('home', 'Home & Living'), ('sparkles', 'Beauty & Skincare'), ('book-open', 'Books & Education'), ('fire', 'Sports & Fitness'), ('puzzle', 'Kids & Toys'), ('cloud-download', 'Digital Products'), ('tag', 'General')], default='tag', help_text='Icon for category display', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Dimensions (e.g., 10x5x2 cm)', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(default=False, help_text="Show 'Bestseller' badge on product"),
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, help_text="Show 'New' badge on product"),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert when stock falls below this number'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (defaults to short description)', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (defaults to product name)', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('physical', 'Physical Product'), ('digital', 'Digital Product')], default='physical', help_text='Physical products are shipped, digital products are downloaded', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (for shipping calculation)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (e.g., Electronics, Fashion)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='URL-friendly name (e.g., electronics, fashion)', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Select the product brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.brand'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Specification name (e.g., Screen Size, RAM, Material)', max_length=100)),
                ('value', models.CharField(help_text='Specification value (e.g., 6.7 inches, 8GB, Cotton)', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
